const alignClass = {
  top: 'bottom-full left-1/2 transform -translate-x-1/2 -translate-y-full',
  bottom: 'top-full left-1/2 transform -translate-x-1/2',
  left: 'top-1/2 right-full transform -translate-y-1/2 -translate-x-full',
  right: 'top-1/2 left-full transform -translate-y-1/2',
  'top-left': 'bottom-full left-0 transform -translate-y-full',
  'top-right': 'bottom-full right-0 transform -translate-y-full',
  'bottom-left': 'top-full left-0',
  'bottom-right': 'top-full right-0',
  'top-left-center': 'bottom-full left-1/4 transform -translate-y-full -translate-x-1/4',
  'top-right-center': 'bottom-full right-1/4 transform -translate-y-full translate-x-1/4',
  'bottom-left-center': 'top-full left-1/4 transform translate-y-full -translate-x-1/4',
  'bottom-right-center': 'top-full right-1/4 transform translate-y-full translate-x-1/4',
  'left-top': 'top-1/4 right-full transform -translate-y-1/4 -translate-x-full',
  'left-bottom': 'bottom-1/4 right-full transform translate-y-1/4 -translate-x-full',
  'right-top': 'top-1/4 left-full transform -translate-y-1/4',
  'right-bottom': 'bottom-1/4 left-full transform translate-y-1/4',
};
