name: Deploy to Jenkins

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}  
          ALGOGO_DEPLOY_TOKEN: ${{ secrets.ALGOGO_DEPLOY_TOKEN }}  
        run: |
          curl -X GET "${{ env.JENKINS_URL }}/generic-webhook-trigger/invoke?token=${{ env.ALGOGO_DEPLOY_TOKEN }}"